spring:
  application:
    name: Dibs
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-authentication-method: client_secret_post # 카카오는 post 방식 필수
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao" # 설정한 것과 동일
            scope:
              - profile_nickname
              # - account_email // 권한 없음
            client-name: Kakao
          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8080/login/oauth2/code/naver"
            scope:
              - name
#              - email
#              - nickname
            client-name: Naver

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id # 카카오의 고유 식별자 필드명은 'id' 입니다.
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response  # 네이버는 response 안에 유저 정보가 있음

  datasource:
    url: jdbc:mysql://localhost:3307/dibs?serverTimezone=UTC&useSSL=false
    username: your_user
    password: your_pass
    driver-class-name: com.mysql.cj.jdbc.Driver


  data:
    redis:
      host: localhost
      port: 6379

  cloud:
    aws:
      credentials:
        access-key: ${S3-ACCESS-KEY}
        secret-key: ${S3-SECRET-KEY}
      s3:
        bucket: ${S3-BUCKET-NAME}
      region:
        static: ap-northeast-2


jwt:
  secret: ${JWT_SECRET_KEY}
  expiration: 86400000
  refresh-expiration: 1209600000