spring:
  config:
    activate:
      on-profile: prod
  security:
    oauth2:
      client:
        registration:
          kakao:
            redirect-uri: "https://${DOMAIN_NAME}/api/login/oauth2/code/kakao"
          naver:
            redirect-uri: "https://${DOMAIN_NAME}/api/login/oauth2/code/naver"
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?serverTimezone=Asia/Seoul&useSSL=false
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate   # 운영에서는 자동 생성하지 않고 검증만
    show-sql: false

jwt:
  cookie:
    secure: true

storage:
  cloudfront:
    domain: https://${CLOUDFRONT_DOMAIN}